loc               = "eastus"
loc-func          = "eastus2"
svc               = "shd"
env               = "dev"
env-short         = "d"
rgn               = "use"
app               = "IAC"
inst              = "01"
clientcode        = "heb"
client            = "hebeler"
vm-os             = "l"
deployment-number = "03"

username    = "azureadmin"
password    = "E@gL3Ey3$!"
vm-size-app = "Standard_D4ads_v5"
vm-size-web = "Standard_D4ads_v5"